name: binary-ext
version: 2.0.4
synopsis: "An alternate with strong-typed errors for `Data.Binary.Get` monad from `binary` package."
description: "An alternate with strong-typed errors for `Data.Binary.Get` monad from `binary` package."
github: "A1-Triard/binary-ext"
license: Apache
author: "Warlock <internalmike@gmail.com>"
maintainer: "Warlock <internalmike@gmail.com>"
copyright: "2017, 2018 Warlock <internalmike@gmail.com>"
category: Data, Parsing
#extra-source-files:

dependencies:
- base >= 4.11 && < 5
- attoparsec
- binary
- bytestring
- conduit >= 1.3.0
- conduit-combinators
- data-binary-ieee754
- errors
- exceptions
- monad-control
- monad-loops
- mono-traversable
- mtl
- scientific
- text
- transformers
- transformers-base

default-extensions:
- BangPatterns
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- StandaloneDeriving
- RankNTypes
- TupleSections
- TypeFamilies
- UndecidableInstances

ghc-options:
- -fmax-pmcheck-iterations=100000000
- -Wall
- -fprint-potential-instances
- -fsimpl-tick-factor=110

library:
  source-dirs: src

tests:
  binary-ext-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HUnit
    - binary-ext
    default-extensions:
    - OverloadedStrings
